using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Tf2DemoSalvage.SdkReference;
using Tf2DemoSalvage.Viewer3D;

namespace Tf2DemoSalvage.Viewer3D.Tests;

/// <summary>
/// How much of Source's declared surface this project handles, counted from the SDK itself.
/// </summary>
/// <remarks>
/// **The hand-written conformance suites are a map; this is the territory.** Sixty entries written
/// by hand cannot cover an engine that declares 489 material parameters, 66 BSP lumps, 54 model
/// structures and 41 temp entity types — and a list typed from memory goes stale the day it is
/// written. So the checklist is EXTRACTED from the headers and diffed against the sets this project
/// maintains, which turns "how far from Source are we" into a number that cannot drift from the
/// truth without the SDK itself changing.
///
/// **The two halves answer different questions and both are needed.** The hand-written suites say
/// what a gap COSTS — "no rocket trails", "halos at the feet" — which no extraction can infer. This
/// says how many there are, and names every one nobody has looked at yet.
///
/// **Skips when the SDK is absent**, like every other test here that needs something not in the
/// repository. Set <c>SOURCE_SDK</c> to point at a checkout.
/// </remarks>
public sealed class SdkCoverageTests
{
    /// <summary>Where the generated report is written.</summary>
    /// <remarks>
    /// Into the repository rather than a temp folder, because the point is to DIFF it between
    /// commits: a number that only exists in a test run cannot show that yesterday's change moved
    /// it. It is generated, so it carries a header saying so.
    /// </remarks>
    private static string ReportPath => Path.GetFullPath(Path.Combine(
        TestContext.CurrentContext.TestDirectory,
        "..", "..", "..", "..", "..",
        "docs", "SDK-COVERAGE.md"));

    [Test]
    public void SdkCoverage_TheSdkSurface_IsCountedAndReported()
    {
        if (SdkInventory.Root is null)
        {
            Assert.Ignore("source-sdk-2013 is not available; set SOURCE_SDK to run this.");
            return;
        }

        IReadOnlyCollection<string> parameters = SdkInventory.ShaderParameters();
        IReadOnlyCollection<string> lumps = SdkInventory.BspLumps();
        IReadOnlyCollection<string> structures = SdkInventory.StudioStructures();
        IReadOnlyCollection<string> messages = SdkInventory.NetMessages();
        IReadOnlyCollection<string> effects = SdkInventory.TempEntities();

        // **The extraction has to be checked before its output means anything.** A regex that
        // matched nothing would report perfect coverage of an empty set, which is the most
        // flattering possible way to be wrong — and exactly the shape of failure this project has
        // hit twice already with instruments that answered confidently about nothing.
        parameters.Count.ShouldBeGreaterThan(400, "SHADER_PARAM extraction found too few to be real");
        lumps.Count.ShouldBeGreaterThan(60, "LUMP_ extraction found too few to be real");
        structures.Count.ShouldBeGreaterThan(40, "mstudio*_t extraction found too few to be real");
        messages.Count.ShouldBeGreaterThan(20, "net message extraction found too few to be real");
        effects.Count.ShouldBeGreaterThan(30, "temp entity extraction found too few to be real");

        string report =
            "# Coverage of Source's declared surface\n\n" +
            "**Generated by `SdkCoverageTests`. Do not edit.** Extracted from `source-sdk-2013` and\n" +
            "diffed against the sets this project maintains, so it cannot drift from the engine\n" +
            "without the engine changing.\n\n" +
            "A name here is something the ENGINE declares, not something this viewer needs equally:\n" +
            "`$cloakPassEnabled` sits on 307 materials and shows nothing until a spy cloaks, while\n" +
            "`$phong` is on 330 and every model is dull without it. `docs/CONFORMANCE.md` carries what\n" +
            "each gap COSTS; this carries how many there are.\n\n" +
            SdkInventory.Report("Material parameters", parameters, ImplementedParameters()) +
            "\n" +
            SdkInventory.Report("Material flags", SdkInventory.MaterialFlags(), ImplementedParameters()) +
            "\n" +
            SdkInventory.Report("BSP lumps", lumps, ImplementedLumps()) +
            "\n" +
            SdkInventory.Report("Studio structures", structures, ImplementedStructures()) +
            "\n" +
            SdkInventory.Report("Network messages", messages, ImplementedMessages()) +
            "\n" +
            SdkInventory.Report("Temp entity effects", effects, []) +
            "\nNone of the temp entity effects are drawn. See `EffectConformanceTests`.\n";

        Directory.CreateDirectory(Path.GetDirectoryName(ReportPath)!);
        File.WriteAllText(ReportPath, report);

        TestContext.Out.WriteLine($"SDK coverage written to {ReportPath}");
        TestContext.Out.WriteLine(
            $"SDK surface: {parameters.Count} material parameters, {lumps.Count} lumps, " +
            $"{structures.Count} studio structures, {messages.Count} messages, {effects.Count} effects");
    }

    [Test]
    public void SdkCoverage_TheStandardMaterialVars_AreFound()
    {
        // **The positive control for the axis added beside it.** A scrape that finds nothing makes
        // EveryMaterialParameterWeClaim pass more easily, not less — an empty denominator can only
        // shrink the set of accusations, so a broken regex there looks exactly like a clean result.
        //
        // Five absence claims in this project have turned out to be facts about the search rather
        // than about the thing searched for, which is why an axis is not trusted until something
        // asserts it found what it must.
        if (SdkInventory.Root is null)
        {
            Assert.Ignore("source-sdk-2013 is not available; set SOURCE_SDK to run this.");
            return;
        }

        IReadOnlyCollection<string> standard = SdkInventory.StandardMaterialVars();

        TestContext.Out.WriteLine(
            $"{standard.Count} standard material vars: {string.Join(", ", standard.Order())}");

        // The three this project reads, named individually. A count alone would pass on any
        // thirteen identifiers the regex happened to catch elsewhere in the header.
        standard.ShouldContain("COLOR");
        standard.ShouldContain("COLOR2");
        standard.ShouldContain("ALPHA");

        // **The negative half, and it matters as much.** The lookbehind is what keeps the match
        // inside the enum; without it the same regex sweeps the whole header and picks up members
        // of BlendType_t, which sits directly below it. BT_NONE appearing here would mean the
        // denominator had quietly become "every capitalised identifier in the file", which would
        // never accuse anything of anything again.
        standard.ShouldNotContain("BT_NONE");
        standard.ShouldNotContain("BT_BLEND");

        standard.Count.ShouldBeGreaterThan(
            8, "ShaderMaterialVars_t declares thirteen members before its count");
    }

    [Test]
    public void EveryMaterialParameterWeClaim_IsOneTheEngineDeclares()
    {
        // **The claim checked in the other direction.** A parameter in our implemented set that the
        // engine never declares is a typo, and a typo there is invisible: the census stops
        // reporting a name no material will ever use, so a misspelling reads as "implemented"
        // forever. Cheap to catch, impossible to notice by hand.
        if (SdkInventory.Root is null)
        {
            Assert.Ignore("source-sdk-2013 is not available; set SOURCE_SDK to run this.");
            return;
        }

        // **All three axes, because the engine splits them three ways.** A shader parameter is what
        // a shader reads; a material flag is a bit set on the material itself and lives in
        // imaterial.h at line 355; a STANDARD var belongs to every shader at once and is declared
        // in shaderlib/BaseShader.h:32.
        //
        // The same mistake has now been made twice with this list, in the same shape both times.
        // Checking against parameters alone reported eight of ours as undeclared and every one was
        // a flag. Adding flags left $color, $color2 and $alpha reported the same way, and every one
        // of those is a standard var. On neither occasion was the code wrong — the inventory had
        // the wrong model of the engine, and said so with an assertion that reads like a finding
        // about our code. Worth remembering before believing this test's next accusation.
        HashSet<string> declared = new(
            SdkInventory.ShaderParameters()
                .Concat(SdkInventory.MaterialFlags())
                .Concat(SdkInventory.StandardMaterialVars())
                .Select(name => name.Replace("_", string.Empty, StringComparison.Ordinal)),
            StringComparer.OrdinalIgnoreCase);

        // What remains is genuinely neither: a vbsp compile flag and a KeyValues key, named here
        // rather than excluded silently.
        string[] notMaterialVariables =
        [
            "include", "%compilenodraw",
        ];

        string[] wrong =
        [
            .. ImplementedParameters()
                .Where(name => !notMaterialVariables.Contains(name, StringComparer.OrdinalIgnoreCase))
                .Where(name => !declared.Contains(name.TrimStart('$', '%').Replace("_", string.Empty, StringComparison.Ordinal))),
        ];

        wrong.ShouldBeEmpty(
            "these are claimed as implemented but Source declares no such shader parameter: " +
            string.Join(", ", wrong));
    }

    /// <summary>The material parameters this project reads.</summary>
    /// <remarks>
    /// **The renderer's own set, not a copy of it.** A mirror maintained here would be a second
    /// source of truth for the same claim, and the two would drift the first time one was edited —
    /// leaving a coverage report that describes a renderer nobody is running. The census exposes it
    /// internally for exactly this, and the diff that matters is against the SDK rather than
    /// against another list of ours.
    /// </remarks>
    private static IReadOnlyCollection<string> ImplementedParameters() =>
        MaterialCensus.ImplementedParameters;

    /// <summary>The BSP lumps this project reads.</summary>
    /// <remarks>
    /// **Hand-maintained, and that is this instrument's one weak joint.** The DENOMINATOR is
    /// extracted from the SDK and cannot go stale; this numerator is a list somebody has to
    /// remember to extend. Adding a reader without adding its name here does not fail anything — it
    /// makes the generated report understate coverage, which is the flattering direction to be
    /// wrong in reverse.
    ///
    /// **A lump belongs here when it is READ, not when it is drawn** (D93). `LUMP_VERTNORMALS` and
    /// `LUMP_VERTNORMALINDICES` are decoded into `MapLevel.Normals` and nothing consumes them yet;
    /// they are handled, because the question this report answers is whether the file is understood.
    /// What each gap COSTS on screen is `docs/CONFORMANCE.md`'s job.
    /// </remarks>
    private static string[] ImplementedLumps() =>
    [
        "LUMP_VERTNORMALS", "LUMP_VERTNORMALINDICES",
        "LUMP_ENTITIES", "LUMP_PLANES", "LUMP_TEXDATA", "LUMP_VERTEXES", "LUMP_NODES",
        "LUMP_TEXINFO", "LUMP_FACES", "LUMP_LIGHTING", "LUMP_LEAFS", "LUMP_EDGES",
        "LUMP_SURFEDGES", "LUMP_MODELS", "LUMP_WORLDLIGHTS", "LUMP_LEAFFACES",
        "LUMP_DISPINFO", "LUMP_DISP_VERTS", "LUMP_GAME_LUMP", "LUMP_OVERLAYS",
        "LUMP_LEAF_AMBIENT_INDEX", "LUMP_LEAF_AMBIENT_LIGHTING", "LUMP_TEXDATA_STRING_DATA",
        "LUMP_TEXDATA_STRING_TABLE", "LUMP_PAKFILE", "LUMP_FACES_HDR", "LUMP_LIGHTING_HDR",
        "LUMP_LEAF_AMBIENT_INDEX_HDR", "LUMP_LEAF_AMBIENT_LIGHTING_HDR",
    ];

    /// <summary>The studio structures this project reads.</summary>
    private static string[] ImplementedStructures() =>
    [
        "mstudiobone_t", "mstudioseqdesc_t", "mstudioanimdesc_t", "mstudiobodyparts_t",
        "mstudiomodel_t", "mstudiomesh_t", "mstudiotexture_t", "mstudioposeparamdesc_t",
        "mstudiomodelgroup_t", "mstudioanim_t", "mstudioanimvalue_t",
    ];

    /// <summary>The network messages this project decodes.</summary>
    /// <remarks>
    /// All of them, which is not a boast: a demo carries no length prefixes, so a message this
    /// project could not read would stop the stream at that byte. "Decode must be total" is a rule
    /// here for that reason, and this is the assertion of it.
    /// </remarks>
    private static string[] ImplementedMessages() =>
    [
        "Tick", "StringCmd", "SetConVar", "SignonState", "Print", "ServerInfo", "SendTable",
        "ClassInfo", "SetPause", "CreateStringTable", "UpdateStringTable", "VoiceInit",
        "VoiceData", "Sounds", "SetView", "FixAngle", "CrosshairAngle", "BSPDecal", "GameEvent",
        "UserMessage", "EntityMessage", "PacketEntities", "TempEntities", "Prefetch", "Menu",
        "GameEventList", "GetCvarValue", "CmdKeyValues", "SetPauseTimed",
    ];
}
