using System;
using System.Collections.Generic;
using System.Linq;

using Tf2DemoSalvage.Content.Assets;
using Tf2DemoSalvage.SdkReference;

namespace Tf2DemoSalvage.Content.Tests.Assets;

/// <summary>
/// Model features declared in <c>studio.h</c> that nothing here reads.
/// </summary>
/// <remarks>
/// **Sixth batch, and generated by the same question as the world one**: which structures has this
/// project already enumerated and never opened? <c>SdkCoverageTests</c> counts 54 <c>mstudio*_t</c>
/// structures in <c>studio.h</c> and <c>StudioLayout</c> pins nine of them. The other forty-five are
/// this list's raw material.
///
/// **A model is not just triangles and a skeleton**, which is the through-line here. Jiggle bones
/// move without animation, flexes reshape the mesh, IK rules pin feet to the ground, and two of
/// TF2's most recognisable effects — the Spy's cloak and a weapon's killstreak sheen — are extra
/// render passes on an otherwise ordinary material.
/// </remarks>
public sealed class UnimplementedModelConformanceTests
{
    /// <summary>Where the engine declares the model structures.</summary>
    private const string Studio = "src/public/studio.h";

    [SetUp]
    public void RequireTheSdk()
    {
        if (!SourceSdk.Available)
        {
            Assert.Ignore(SourceSdk.Missing);
        }
    }

    [Test]
    public void Models_AJiggleBone_MovesWithoutAnAnimation()
    {
        // **STUDIO_PROC_JIGGLE, procedure type 5** (studio.h:107), with seven behaviour flags at
        // lines 186-192: flexible or rigid, yaw, pitch, angle and length constraints, and a base
        // spring. A jiggle bone is simulated from the model's motion rather than keyframed.
        //
        // TF2 uses these on hats, cloth and antennae — anything that should lag behind a running
        // player. Unimplemented, they hold their rest pose, so a Demoman's beard and every
        // dangling cosmetic are rigid.
        //
        // The flags are pinned here because a partial implementation that ignores the constraints
        // produces motion without limits, which looks worse than none.
        IReadOnlyDictionary<string, int> studio = SourceSdk.Constants(Studio);

        studio["STUDIO_PROC_JIGGLE"].ShouldBe(5);
        studio["JIGGLE_IS_FLEXIBLE"].ShouldBe(0x01);
        studio["JIGGLE_IS_RIGID"].ShouldBe(0x02);
        studio["JIGGLE_HAS_LENGTH_CONSTRAINT"].ShouldBe(0x20);

        Assert.Ignore(
            "jiggle bones are not simulated, so hats, cloth and antennae hold their rest pose. " +
            "The constraint flags are pinned above because motion without them looks worse than " +
            "no motion.");
    }

    [Test]
    public void Models_AFlex_ReshapesTheMeshWithoutMovingABone()
    {
        // mstudioflex_t (studio.h:1144). Flexes are vertex deltas driven by a controller, which is
        // how faces emote and how some weapons deform. Networked as m_flexWeight.
        //
        // Nothing here reads them, so every model wears its neutral expression. On TF2 that is most
        // visible on taunts and death poses.
        StructureNames().ShouldContain("mstudioflex_t");

        Assert.Ignore(
            "flexes are not read, so faces never emote and flex-driven deformation is absent.");
    }

    [Test]
    public void Models_AnIkRule_HoldsAFootWhereTheAnimationPutIt()
    {
        // mstudioikrule_t (studio.h:557) with mstudioiklink_t (1277). IK rules keep a foot planted
        // while the rest of the body moves, correcting the animation against the ground.
        //
        // Without them a running player's feet slide, which is the classic tell of a model drawn
        // from animation data alone. Worth specifying even though it is subtle, because it is
        // exactly the sort of thing that gets attributed to the animation being wrong rather than
        // to IK being absent.
        StructureNames().ShouldContain("mstudioikrule_t");
        StructureNames().ShouldContain("mstudioiklink_t");

        Assert.Ignore(
            "IK rules are not applied, so feet slide rather than staying planted — which reads as " +
            "a wrong animation rather than as missing IK.");
    }

    [Test]
    public void Models_AHitboxSet_DescribesWhereAModelCanBeHit()
    {
        // mstudiobbox_t (453) and mstudiohitboxset_t (1686). Not drawn in a normal view, but this is
        // a demo REVIEW tool: showing where a shot landed relative to a hitbox is the single most
        // asked-for overlay in a competitive review, and the data is in the model.
        //
        // Specified here rather than dismissed as non-visual because the audience makes it
        // load-bearing, in the same way surf and jump made the usercmd stream load-bearing.
        StructureNames().ShouldContain("mstudiobbox_t");
        StructureNames().ShouldContain("mstudiohitboxset_t");

        Assert.Ignore(
            "hitboxes are not read. Not needed to draw a scene, but a demo review tool that cannot " +
            "show where a shot landed relative to a hitbox is missing the thing reviewers want.");
    }

    [Test]
    public void Models_LevelOfDetail_IsChosenByDistance()
    {
        // ModelLODHeader_t carries switchPoint, a float distance at which that LOD takes over — this
        // project derives the 12-byte stride in VertexFileStructTests and reads meshes from LOD 0
        // only.
        //
        // Drawing LOD 0 always is correct and expensive: it is the highest detail, so the picture is
        // right and the triangle count is the worst case at every distance. The same trade as the
        // PVS, and worth recording next to it.
        VertexFileLayout.VtxLodStride.ShouldBe(12);

        Assert.Ignore(
            "LOD 0 is always drawn and switchPoint is ignored. Correct and expensive — the highest " +
            "detail at every distance — which is the same trade as ignoring the PVS.");
    }

    [Test]
    public void Models_CloakAndSheen_AreExtraRenderPasses()
    {
        // **Two of TF2's most recognisable effects, and both are second passes.**
        // vertexlitgeneric_dx9.cpp:92 declares $cloakpassenabled "Enables cloak render in a second
        // pass" and line 98 $sheenpassenabled for the weapon sheen; line 288 gates the cloak pass on
        // the material supporting it.
        //
        // A material declaring these draws normally without them, so a cloaked Spy renders fully
        // visible and a killstreak weapon has no shine. The first of those is not a cosmetic
        // difference in a demo review — it changes what the viewer believes was on screen.
        //
        // The 307 materials that declare cloak support are a CAPABILITY count rather than a gap:
        // the pass runs per frame only while m_cloakFactor is between 0 and 1.
        Dictionary<string, string> defaults = ShaderDefaults();

        defaults.ShouldContainKey("CLOAKPASSENABLED");
        defaults.ShouldContainKey("SHEENPASSENABLED");
        defaults["CLOAKPASSENABLED"].ShouldBe("0");

        Assert.Ignore(
            "cloak and sheen passes are not implemented, so a cloaked Spy draws fully visible. " +
            "That is not cosmetic in a review tool — it changes what the viewer believes was on " +
            "screen at that tick.");
    }

    [Test]
    public void Models_MostOfTheFormat_IsStillUnread()
    {
        // **The honest denominator.** studio.h declares 54 mstudio*_t structures and StudioLayout
        // pins nine. This states the ratio rather than any one gap, so the score cannot drift while
        // individual entries are closed.
        int declared = StructureNames().Count;

        declared.ShouldBeGreaterThan(40, "the structure scan found too few to be right");

        Assert.Ignore(
            $"{declared} mstudio structures are declared and this project reads nine of them. The " +
            "individual gaps above are examples rather than the list.");
    }

    /// <summary>Every studio structure the engine declares.</summary>
    private static HashSet<string> StructureNames() =>
        SourceSdk.Names(
            "src/public",
            "studio.h",
            new System.Text.RegularExpressions.Regex(
                @"^struct (mstudio[a-z_]+_t)",
                System.Text.RegularExpressions.RegexOptions.Multiline,
                TimeSpan.FromSeconds(10)));

    /// <summary>The defaults the model shader declares for its parameters.</summary>
    private static Dictionary<string, string> ShaderDefaults()
    {
        string source = SourceSdk.Text("src/materialsystem/stdshaders/vertexlitgeneric_dx9.cpp")
            ?? throw new InvalidOperationException("vertexlitgeneric_dx9.cpp is missing");

        Dictionary<string, string> defaults = new(StringComparer.Ordinal);

        foreach (System.Text.RegularExpressions.Match hit in
            System.Text.RegularExpressions.Regex.Matches(
                source,
                @"SHADER_PARAM\(\s*([A-Z0-9_]+)\s*,\s*[A-Z_]+\s*,\s*""([^""]*)""",
                System.Text.RegularExpressions.RegexOptions.None,
                TimeSpan.FromSeconds(10)))
        {
            defaults.TryAdd(hit.Groups[1].Value, hit.Groups[2].Value);
        }

        defaults.Count.ShouldBeGreaterThan(20, "no shader parameters were extracted");

        return defaults;
    }
}
