using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.Extensions.Logging;

using Tf2DemoSalvage.Core.Scene;

namespace Tf2DemoSalvage.Scene.Tests;

/// <summary>
/// Working out which model is in a player's hands, and reading the schema that says so once.
/// </summary>
/// <remarks>
/// **This was <c>MainForm.WeaponModelFor</c>, <c>WeaponModel</c> and <c>ItemDefinitions</c> with two
/// fields beside them** (B188, D90). None of it was window work — it is two lookups into
/// <c>items_game.txt</c> — and none of it had a test, because reaching it meant a form.
///
/// **Two routes, and the second is needed more often than it looks.** A demo names the item a player
/// holds (<c>m_iItemDefinitionIndex</c>) and the schema turns that into a model; but measured on
/// z1800, **22 of 56** held weapons never send one, so the weapon's own class is used to find the
/// stock item instead. Together they answered for 56 of 56. Both routes are pinned here, and so is
/// the order between them.
///
/// The schema is authored from the KeyValues format rather than produced by our own writer — a
/// fixture generated by the code under test proves the two agree and nothing else.
/// </remarks>
public sealed class WeaponModelsTests
{
    [Test]
    public void For_APlayerHoldingAKnownItem_AnswersThatItemsModel()
    {
        // The first route: the demo said which item, and the schema knows it.
        WeaponModels weapons = Weapons();

        weapons.For(Soldier() with { WeaponItem = RocketLauncherItem }).ShouldBe(RocketLauncherModel);
    }

    [Test]
    public void For_APlayerWhoseItemWasNeverSent_FallsBackToTheStockItemForTheirWeaponClass()
    {
        // **The route that carries 22 of 56.** Without it those weapons resolve to nothing and the
        // hand is empty — which reads as a rendering fault rather than as a missing field.
        WeaponModels weapons = Weapons();

        weapons.For(Soldier() with { WeaponItem = null, WeaponClass = RocketLauncherServerClass })
            .ShouldBe(StockRocketLauncherModel);
    }

    [Test]
    public void For_APlayerWithBothAnItemAndAClass_PrefersTheItem()
    {
        // **The order matters and is the whole reason both exist.** The item is what the player
        // actually equipped; the class only knows the stock version, so preferring it would draw a
        // stock rocket launcher for every unusual and reskin in the game.
        WeaponModels weapons = Weapons();

        weapons.For(
                Soldier() with
                {
                    WeaponItem = RocketLauncherItem,
                    WeaponClass = RocketLauncherServerClass,
                })
            .ShouldBe(RocketLauncherModel);
    }

    [Test]
    public void For_APlayerHoldingNothing_AnswersNull()
    {
        // A player between weapons, or one whose class the demo never stated.
        Weapons().For(Soldier() with { WeaponItem = null, WeaponClass = null }).ShouldBeNull();
    }

    [Test]
    public void For_AnItemTheSchemaDoesNotKnow_AnswersNull()
    {
        // A demo from a later era than the installed schema, which is the ordinary case for this
        // project: answering null draws nothing rather than drawing the wrong weapon.
        Weapons().For(Soldier() with { WeaponItem = 999_999 }).ShouldBeNull();
    }

    /// <remarks>
    /// **A known item that names no model has answered, and the stock item is not asked** (B105's open item). A TF
    /// weapon's world model is its item's whenever the item is valid — `CTFWeaponBase::GetWorldModel` returns
    /// `GetPlayerDisplayModel` as it is, "" included, and reaches the script only for an invalid item
    /// (tf_weaponbase.cpp:681-701) — so the class route, this project's stand-in for that script, is for an item the
    /// schema cannot name. The Fists and the four spellbooks are the shipped case. The control is the class route
    /// itself: <see cref="For_APlayerWhoseItemWasNeverSent_FallsBackToTheStockItemForTheirWeaponClass"/> and
    /// <see cref="AllWornIn_ForAnItemTheSchemaDoesNotKnow_FallsBackToTheStockModelForItsClass"/>, same class, same stock item.
    /// </remarks>
    [Test]
    public void For_AKnownItemWhoseOwnModelPlayerIsEmpty_AnswersEmptyNotTheStockModel()
    {
        Weapons().For(NoModelLauncherItem, RocketLauncherServerClass, forClass: 3).ShouldBe(string.Empty);
    }

    /// <remarks>
    /// **The first-person model is `model_player` whatever `model_world` says** — the control that keeps the world rule out
    /// of this route. The viewmodel attachment is built from `pItem->GetPlayerDisplayModel( iClass, team )`
    /// (econ_entity.cpp:1167); `model_world` is read only by the THIRD-person `CTFWeaponBase::GetWorldModel`
    /// (tf_weaponbase.cpp:686-687) and the loadout panel. `For` answers the viewmodel (`MomentScene`, B222), so a Hot Hand
    /// here is the glove the pyro sees on his own hand.
    /// </remarks>
    [Test]
    public void For_AnItemThatAlsoNamesAModelWorld_AnswersItsModelPlayer()
    {
        Weapons().For(GloveItem, GloveServerClass, forClass: Pyro).ShouldBe(GlovePlayerModel);
    }

    [Test]
    public void For_WithNoInstall_AnswersNullAndSaysWhyOnce()
    {
        // **Reported once rather than per frame, and counted rather than silent.** A viewer with no
        // TF2 draws no first-person weapons at all, which is indistinguishable from a broken
        // resolver unless it says so.
        RecordingLogger log = new();
        WeaponModels weapons = new(read: _ => null, log);

        for (int frame = 0; frame < 5; frame++)
        {
            weapons.For(Soldier() with { WeaponItem = RocketLauncherItem }).ShouldBeNull();
        }

        log.Count("no items_game.txt").ShouldBe(1);
    }

    [Test]
    public void For_AskedRepeatedly_ReadsTheSchemaOnce()
    {
        // **It is eight megabytes and this is asked every frame.** Re-reading it per call is the
        // "once per X cost wearing the clothes of a cache" shape that B191 was about.
        List<string> reads = [];
        WeaponModels weapons = new(
            path =>
            {
                reads.Add(path);
                return Schema();
            },
            new RecordingLogger());

        for (int frame = 0; frame < 5; frame++)
        {
            weapons.For(Soldier() with { WeaponItem = RocketLauncherItem });
        }

        reads.Count.ShouldBe(1);
    }

    // A `For_WithNoHolder_Refuses` case was written here and deleted: `ScenePlayer` is a record
    // STRUCT, so it cannot be null and the guard it tested was a no-op the analyzer rejected
    // outright (CA2264). See `docs/memory/nullable-pattern-on-a-struct-is-dead-code.md` — a test for
    // a branch that cannot be taken passes for ever and measures nothing.

    [Test]
    public void Constructor_WithNoLogger_Refuses()
    {
        Should.Throw<ArgumentNullException>(() => new WeaponModels(_ => null, render: null!));
    }

    /// <remarks>
    /// **The walk that decides whether a hat is ever LOADED** (B379). `WeaponPropModels.Resolve`
    /// replaces a prop's model with `GetPlayerDisplayModel` at draw time for every prop carrying an
    /// item index — `CEconEntity::UpdateModelToClass` lets the item win over the networked one
    /// (`econ_entity.cpp:411`) — so the model that reaches the renderer is named by the ITEM and not
    /// by the track. `DemoModels.Needed` builds the asset load list by walking tracks, so without
    /// this walk the loader is never asked, `MapAssets.Geometry` answers null from a dictionary that
    /// has no such key, and the prop packs no batches.
    ///
    /// **Measured before it was written**: on `20130518_0313_cp_granary_blu_blu`, 34 of the 66 models
    /// that packed no geometry were absent from the load list and named by no track — every one a
    /// `models/player/items/…` cosmetic. Thirteen went undrawn on each frame while the asset load
    /// reported `ASKED FOR 166; HAVE 166; MISSING 0` and was telling the truth about its own list.
    /// </remarks>
    [Test]
    public void AllWornIn_ForATrackCarryingAnItemAndNoModelPath_NamesTheItemsOwnModel()
    {
        ScenePropTrack wearable = new(entityIndex: 7, string.Empty)
        {
            ItemDefinitionIndex = RocketLauncherItem,
            ClassName = RocketLauncherServerClass,
        };

        wearable.Add(0, new ScenePose());

        Weapons()
            .AllWornIn(DemoTimeline.ForEverything(props: [wearable]))
            .ShouldContain(RocketLauncherModel);
    }

    /// <remarks>
    /// **A track carrying no item contributes nothing**, which is what keeps the walk from being
    /// "yield everything": an ordinary prop's model is named by the wire and already covered by the
    /// track walk in `DemoModels.Needed`.
    ///
    /// **This does NOT test the `ItemDefinitionIndex` guard, and saying so is the point.** Removing
    /// that guard reddens nothing, because `For(null, …)` returns null and the walk yields nothing
    /// either way — the guard saves a call and decides no behaviour. A test claiming to pin it would
    /// be one that cannot fail, which is worse than not having one.
    /// </remarks>
    [Test]
    public void AllWornIn_ForATrackCarryingNoItem_NamesNothing()
    {
        ScenePropTrack crate = new(entityIndex: 7, "models/props/crate.mdl");

        crate.Add(0, new ScenePose());

        Weapons().AllWornIn(DemoTimeline.ForEverything(props: [crate])).ShouldBeEmpty();
    }

    /// <remarks>
    /// **The per-class axis, which is why the walk asks nine times rather than once**
    /// (`model_player_per_class`, `tf_item_schema.cpp:489`). A worn item's model differs per class and
    /// the wearer's class is a per-tick fact, so a load list built for whoever wears it right now is
    /// missing whatever they switch to — and geometry is loaded once before the first frame, which
    /// D86 makes a hard requirement rather than a preference.
    ///
    /// **Both variants asserted, because either alone passes against a walk pinned to one class.**
    /// A single-class assertion is the shape that let the first version of this test survive a
    /// sabotage that limited the loop to class zero.
    /// </remarks>
    [Test]
    public void AllWornIn_ForAnItemWhoseModelDiffersPerClass_NamesEveryClasssVariant()
    {
        ScenePropTrack hat = new(entityIndex: 7, string.Empty) { ItemDefinitionIndex = HatItem };

        hat.Add(0, new ScenePose());

        List<string> worn = [.. Weapons().AllWornIn(DemoTimeline.ForEverything(props: [hat]))];

        worn.ShouldContain(ScoutHatModel);
        worn.ShouldContain(SoldierHatModel);
    }

    /// <remarks>
    /// **An item's own models are WORN, so they must be loaded skinned** (B406). The owner: *"the cosmetic never roots on any
    /// spawn, so it's always there … down near the feet"*. `WeaponPropModels.Resolve` gives a worn prop its item's model at draw
    /// time, and `DemoModels.Worn` — the set `LoadFrames` is told `mustSkin` from — collected only models a TRACK named, so an
    /// item-named cosmetic was loaded baked, never bone-merged, and drawn at its wearer's origin: the feet, every life. Both
    /// per-class variants asserted, for the reason the test above gives.
    /// </remarks>
    [Test]
    public void Worn_ForAPathlessHatCarryingAnItem_IncludesEveryClasssModel()
    {
        ScenePropTrack hat = new(entityIndex: 7, string.Empty) { ItemDefinitionIndex = HatItem, AttachedTo = 3 };

        hat.Add(0, new ScenePose());

        HashSet<string> worn = DemoModels.Worn(DemoTimeline.ForEverything(props: [hat]), Weapons());

        worn.ShouldContain(ScoutHatModel);
        worn.ShouldContain(SoldierHatModel);
    }

    /// <remarks>
    /// **The class route, which the walk reaches only by passing the track's own class name.** An
    /// item index the schema has never heard of is the ordinary case for a demo recorded on a later
    /// build than the installed game — measured on z1800, 22 of 56 held weapons send no item at all —
    /// and `For` then translates the SERVER class through `WeaponScriptName.Candidates` to find the
    /// stock item. Dropping `track.ClassName` here loses every one of those models silently, and no
    /// test saw it until this one.
    /// </remarks>
    [Test]
    public void AllWornIn_ForAnItemTheSchemaDoesNotKnow_FallsBackToTheStockModelForItsClass()
    {
        ScenePropTrack weapon = new(entityIndex: 7, string.Empty)
        {
            ItemDefinitionIndex = UnknownItem,
            ClassName = RocketLauncherServerClass,
        };

        weapon.Add(0, new ScenePose());

        Weapons()
            .AllWornIn(DemoTimeline.ForEverything(props: [weapon]))
            .ShouldContain(StockRocketLauncherModel);
    }

    /// <remarks>
    /// **A weapon whose item names a `model_world` draws it, so the load list must hold it** (B379's rule, RISKS B105).
    /// `WeaponPropModels.Resolve` gives a held weapon its item's `model_world` (tf_weaponbase.cpp:686-687), which no track
    /// need name: an attach-to-hands weapon that sends no world index carries only the carrier's arms on the wire
    /// (econ_entity.cpp:398-402). `Needed`, `ToPack` and `Worn` all take this walk, so a `model_world` missing from it is
    /// never loaded and packs nothing — silently, as the hats of B379 did.
    /// </remarks>
    [Test]
    public void AllWornIn_ForAWeaponWhoseItemNamesAModelWorld_NamesTheModelWorld()
    {
        ScenePropTrack glove = new(entityIndex: 7, "models/weapons/c_models/c_pyro_arms.mdl")
        {
            ItemDefinitionIndex = GloveItem,
            ClassName = GloveServerClass,
        };

        glove.Add(0, new ScenePose());

        Weapons()
            .AllWornIn(DemoTimeline.ForEverything(props: [glove]))
            .ShouldContain(GloveWorldModel);
    }

    /// <summary>A resolver over a hand-authored schema.</summary>
    private static WeaponModels Weapons() => new(_ => Schema(), new RecordingLogger());

    private static ScenePlayer Soldier() =>
        new(EntityIndex: 3, X: 0f, Y: 0f, Z: 0f, Team: SceneTeams.Red, Health: 200, PlayerClass: 3);

    private const int RocketLauncherItem = 18;

    /// <summary>What a demo's schema actually names the weapon, which is not the script name.</summary>
    /// <remarks>
    /// **The distinction cost this fixture a failing test against correct code.** The wire carries a
    /// SERVER class — <c>CTFRocketLauncher</c> — and <c>WeaponScriptName.Candidates</c>
    /// translates it into script names like <c>tf_weapon_rocketlauncher</c>, which are what
    /// <c>item_class</c> holds. Putting the script name on the player skips the translation the
    /// production path depends on, so the test was measuring a shape no demo produces.
    /// </remarks>
    private const string RocketLauncherServerClass = "CTFRocketLauncher";

    private const string RocketLauncherModel = "models/weapons/c_models/c_rocketlauncher.mdl";

    private const string StockRocketLauncherModel =
        "models/weapons/w_models/w_rocketlauncher.mdl";

    /// <summary>
    /// A minimal <c>items_game.txt</c>, written from the KeyValues format rather than our reader.
    /// </summary>
    /// <remarks>
    /// **Two entries and they differ on purpose.** One is reachable by item index and the other only
    /// by weapon class, so a resolver that ignored either route answers wrongly for one of them —
    /// which a single-entry schema could not show.
    ///
    /// **The <c>baseitem</c> key on the second is load bearing**, and leaving it out is what the
    /// first version of this fixture did. <c>ModelForClass</c> looks for the STOCK item of a class,
    /// so an entry that does not claim to be one is skipped and the class route answers null — the
    /// test failed against correct code until the fixture said what a real schema says.
    /// </remarks>
    private static byte[] Schema() =>
        Encoding.UTF8.GetBytes(
            $$"""
            "items_game"
            {
                "items"
                {
                    "{{RocketLauncherItem}}"
                    {
                        "name"              "The Rocket Launcher"
                        "item_class"        "tf_weapon_rocketlauncher"
                        "model_player"      "{{RocketLauncherModel}}"
                    }
                    "205"
                    {
                        "name"              "Stock Rocket Launcher"
                        "item_class"        "tf_weapon_rocketlauncher"
                        "baseitem"          "1"
                        "model_player"      "{{StockRocketLauncherModel}}"
                    }
                    "{{NoModelLauncherItem}}"
                    {
                        "name"              "A Launcher That Names No Model"
                        "item_class"        "tf_weapon_rocketlauncher"
                        "model_player"      ""
                    }
                    "{{GloveItem}}"
                    {
                        "name"              "A Glove With A World Model"
                        "item_class"        "tf_weapon_slap"
                        "attach_to_hands"   "1"
                        "model_player"      "{{GlovePlayerModel}}"
                        "model_world"       "{{GloveWorldModel}}"
                    }
                    "{{HatItem}}"
                    {
                        "name"              "A Hat With Two Faces"
                        "item_class"        "tf_wearable"
                        "model_player_per_class"
                        {
                            "scout"         "{{ScoutHatModel}}"
                            "soldier"       "{{SoldierHatModel}}"
                        }
                    }
                }
            }
            """);

    /// <summary>An item whose model differs per class, which is what a real hat does.</summary>
    /// <remarks>
    /// **Added because three sabotages reddened nothing.** The first version of the worn-model tests
    /// used only the rocket launcher, which the schema knows by index with one `model_player` — so
    /// `For` answered from the item route for every class, and a walk pinned to a single class passed
    /// just as well as one covering all nine. `model_player_per_class` is what makes the class axis
    /// observable at all, and `docs/memory/most-of-a-decoder-is-untested.md` is the rule: a sabotage
    /// that reddens nothing names the missing input, and the missing input was here rather than in an
    /// assertion.
    /// </remarks>
    private const int HatItem = 1000;

    private const string ScoutHatModel = "models/player/items/scout/two_faces.mdl";

    private const string SoldierHatModel = "models/player/items/soldier/two_faces.mdl";

    /// <summary>An item index the schema has never heard of, for the class fallback.</summary>
    private const int UnknownItem = 4242;

    /// <summary>A known item whose own `model_player` is "", of a class whose stock item names a model.</summary>
    private const int NoModelLauncherItem = 196;

    /// <summary>An item naming a `model_world` apart from its `model_player`, shaped as the shipped Hot Hand (1181).</summary>
    private const int GloveItem = 1181;

    private const string GloveServerClass = "CTFSlap";

    private const string GlovePlayerModel = "models/weapons/c_models/c_slapping_glove/c_slapping_glove.mdl";

    private const string GloveWorldModel = "models/weapons/c_models/c_slapping_glove/w_slapping_glove.mdl";

    /// <summary>`TF_CLASS_PYRO`, the Hot Hand's only class.</summary>
    private const int Pyro = 7;
}
