using System;
using System.Collections.Generic;
using System.Text;

using Microsoft.Extensions.Logging;

using Tf2DemoSalvage.Core.Scene;

namespace Tf2DemoSalvage.Scene.Tests;

/// <summary>
/// Working out which model is in a player's hands, and reading the schema that says so once.
/// </summary>
/// <remarks>
/// **This was <c>MainForm.WeaponModelFor</c>, <c>WeaponModel</c> and <c>ItemDefinitions</c> with two
/// fields beside them** (B188, D90). None of it was window work — it is two lookups into
/// <c>items_game.txt</c> — and none of it had a test, because reaching it meant a form.
///
/// **Two routes, and the second is needed more often than it looks.** A demo names the item a player
/// holds (<c>m_iItemDefinitionIndex</c>) and the schema turns that into a model; but measured on
/// z1800, **22 of 56** held weapons never send one, so the weapon's own class is used to find the
/// stock item instead. Together they answered for 56 of 56. Both routes are pinned here, and so is
/// the order between them.
///
/// The schema is authored from the KeyValues format rather than produced by our own writer — a
/// fixture generated by the code under test proves the two agree and nothing else.
/// </remarks>
public sealed class WeaponModelsTests
{
    [Test]
    public void For_APlayerHoldingAKnownItem_AnswersThatItemsModel()
    {
        // The first route: the demo said which item, and the schema knows it.
        WeaponModels weapons = Weapons();

        weapons.For(Soldier() with { WeaponItem = RocketLauncherItem }).ShouldBe(RocketLauncherModel);
    }

    [Test]
    public void For_APlayerWhoseItemWasNeverSent_FallsBackToTheStockItemForTheirWeaponClass()
    {
        // **The route that carries 22 of 56.** Without it those weapons resolve to nothing and the
        // hand is empty — which reads as a rendering fault rather than as a missing field.
        WeaponModels weapons = Weapons();

        weapons.For(Soldier() with { WeaponItem = null, WeaponClass = RocketLauncherServerClass })
            .ShouldBe(StockRocketLauncherModel);
    }

    [Test]
    public void For_APlayerWithBothAnItemAndAClass_PrefersTheItem()
    {
        // **The order matters and is the whole reason both exist.** The item is what the player
        // actually equipped; the class only knows the stock version, so preferring it would draw a
        // stock rocket launcher for every unusual and reskin in the game.
        WeaponModels weapons = Weapons();

        weapons.For(
                Soldier() with
                {
                    WeaponItem = RocketLauncherItem,
                    WeaponClass = RocketLauncherServerClass,
                })
            .ShouldBe(RocketLauncherModel);
    }

    [Test]
    public void For_APlayerHoldingNothing_AnswersNull()
    {
        // A player between weapons, or one whose class the demo never stated.
        Weapons().For(Soldier() with { WeaponItem = null, WeaponClass = null }).ShouldBeNull();
    }

    [Test]
    public void For_AnItemTheSchemaDoesNotKnow_AnswersNull()
    {
        // A demo from a later era than the installed schema, which is the ordinary case for this
        // project: answering null draws nothing rather than drawing the wrong weapon.
        Weapons().For(Soldier() with { WeaponItem = 999_999 }).ShouldBeNull();
    }

    [Test]
    public void For_WithNoInstall_AnswersNullAndSaysWhyOnce()
    {
        // **Reported once rather than per frame, and counted rather than silent.** A viewer with no
        // TF2 draws no first-person weapons at all, which is indistinguishable from a broken
        // resolver unless it says so.
        RecordingLogger log = new();
        WeaponModels weapons = new(read: _ => null, log);

        for (int frame = 0; frame < 5; frame++)
        {
            weapons.For(Soldier() with { WeaponItem = RocketLauncherItem }).ShouldBeNull();
        }

        log.Count("no items_game.txt").ShouldBe(1);
    }

    [Test]
    public void For_AskedRepeatedly_ReadsTheSchemaOnce()
    {
        // **It is eight megabytes and this is asked every frame.** Re-reading it per call is the
        // "once per X cost wearing the clothes of a cache" shape that B191 was about.
        List<string> reads = [];
        WeaponModels weapons = new(
            path =>
            {
                reads.Add(path);
                return Schema();
            },
            new RecordingLogger());

        for (int frame = 0; frame < 5; frame++)
        {
            weapons.For(Soldier() with { WeaponItem = RocketLauncherItem });
        }

        reads.Count.ShouldBe(1);
    }

    // A `For_WithNoHolder_Refuses` case was written here and deleted: `ScenePlayer` is a record
    // STRUCT, so it cannot be null and the guard it tested was a no-op the analyzer rejected
    // outright (CA2264). See `docs/memory/nullable-pattern-on-a-struct-is-dead-code.md` — a test for
    // a branch that cannot be taken passes for ever and measures nothing.

    [Test]
    public void Constructor_WithNoLogger_Refuses()
    {
        Should.Throw<ArgumentNullException>(() => new WeaponModels(_ => null, render: null!));
    }

    /// <summary>A resolver over a hand-authored schema.</summary>
    private static WeaponModels Weapons() => new(_ => Schema(), new RecordingLogger());

    private static ScenePlayer Soldier() =>
        new(EntityIndex: 3, X: 0f, Y: 0f, Z: 0f, Team: SceneTeams.Red, Health: 200, PlayerClass: 3);

    private const int RocketLauncherItem = 18;

    /// <summary>What a demo's schema actually names the weapon, which is not the script name.</summary>
    /// <remarks>
    /// **The distinction cost this fixture a failing test against correct code.** The wire carries a
    /// SERVER class — <c>CTFRocketLauncher</c> — and <c>WeaponScriptName.Candidates</c>
    /// translates it into script names like <c>tf_weapon_rocketlauncher</c>, which are what
    /// <c>item_class</c> holds. Putting the script name on the player skips the translation the
    /// production path depends on, so the test was measuring a shape no demo produces.
    /// </remarks>
    private const string RocketLauncherServerClass = "CTFRocketLauncher";

    private const string RocketLauncherModel = "models/weapons/c_models/c_rocketlauncher.mdl";

    private const string StockRocketLauncherModel =
        "models/weapons/w_models/w_rocketlauncher.mdl";

    /// <summary>
    /// A minimal <c>items_game.txt</c>, written from the KeyValues format rather than our reader.
    /// </summary>
    /// <remarks>
    /// **Two entries and they differ on purpose.** One is reachable by item index and the other only
    /// by weapon class, so a resolver that ignored either route answers wrongly for one of them —
    /// which a single-entry schema could not show.
    ///
    /// **The <c>baseitem</c> key on the second is load bearing**, and leaving it out is what the
    /// first version of this fixture did. <c>ModelForClass</c> looks for the STOCK item of a class,
    /// so an entry that does not claim to be one is skipped and the class route answers null — the
    /// test failed against correct code until the fixture said what a real schema says.
    /// </remarks>
    private static byte[] Schema() =>
        Encoding.UTF8.GetBytes(
            $$"""
            "items_game"
            {
                "items"
                {
                    "{{RocketLauncherItem}}"
                    {
                        "name"              "The Rocket Launcher"
                        "item_class"        "tf_weapon_rocketlauncher"
                        "model_player"      "{{RocketLauncherModel}}"
                    }
                    "205"
                    {
                        "name"              "Stock Rocket Launcher"
                        "item_class"        "tf_weapon_rocketlauncher"
                        "baseitem"          "1"
                        "model_player"      "{{StockRocketLauncherModel}}"
                    }
                }
            }
            """);
}
