using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Text;

using Microsoft.Extensions.Logging.Abstractions;

using Tf2DemoSalvage.Audio;

namespace Tf2DemoSalvage.Audio.Tests;

/// <summary>
/// Decoding a named sound once, and moving every decode out of the frame that would have paid for it.
/// </summary>
/// <remarks>
/// **The engine owns this and reaches it through an interface** — <c>IEngineSound</c> declares
/// <c>PrecacheSound</c>, <c>IsSoundPrecached</c> and <c>PrefetchSound</c> together
/// (<c>src/public/engine/IEngineSound.h:89-91</c>), and game code asks rather than holding samples:
/// <c>CBaseEntity::PrecacheSound</c> is one line, <c>enginesound-&gt;PrecacheSound( name, true )</c>
/// at <c>SoundEmitterSystem.cpp:1507</c>.
///
/// Ours was <c>MainForm.Sample</c> with <c>_soundCache</c>, <c>_soundsUnopened</c> and
/// <c>_precaching</c> beside it, so **none of it had a test**: reaching it needed an STA thread, a
/// device and a TF2 install (B188, B184).
///
/// The files here are hand-built RIFF/WAVE rather than produced by our own writer — a fixture
/// generated by the code under test proves the two agree and nothing else
/// (<c>docs/memory/put-the-real-file-in-the-fixture.md</c>).
/// </remarks>
public sealed class SoundCacheTests
{
    [Test]
    public void Sample_WithNoReadSource_IsSilentRatherThanThrowing()
    {
        // **Every frame on a machine with no TF2 takes this path.** The viewer is meant to open a
        // demo without the game installed, so an absent archive set is an ordinary state rather
        // than an error — and the cache is asked for sounds from the first tick played.
        SoundCache cache = new(NullLogger.Instance);

        cache.Sample("weapons/shotgun_shoot.wav").ShouldBeNull();
    }

    [Test]
    public void Sample_ForTheSameNameTwice_ReadsTheFileOnce()
    {
        // **The whole reason the type exists.** A decode is a VPK read plus a full decode, on the
        // thread that draws — so a second read is a second freeze.
        List<string> reads = [];
        SoundCache cache = Cache(reads);

        cache.Sample("ambient/indoors.wav");
        cache.Sample("ambient/indoors.wav");

        reads.Count.ShouldBe(1);
    }

    [Test]
    public void Sample_ForTwoDifferentNames_ReadsEachOfThem()
    {
        // **The control for the case above**, without which "reads once" is indistinguishable from
        // "reads once ever" — a cache keyed on nothing would pass the first test and silence the
        // whole match.
        List<string> reads = [];
        SoundCache cache = Cache(reads);

        cache.Sample("ambient/indoors.wav");
        cache.Sample("ambient/outdoors.wav");

        reads.Count.ShouldBe(2);
    }

    [Test]
    public void Sample_ForANameTheInstallLacks_IsRememberedRatherThanRetried()
    {
        // A missing sound must not be looked for sixty times a second — that buries the log in one
        // repeated line, which is how a real missing asset stops being noticeable.
        //
        // **Counted as "reads AFTER the first play" rather than as a total**, because a miss is not
        // one read: `SoundFile.Open` walks the containers a sound may ship in, so one absent
        // `.wav` costs a lookup per container. The first version asserted a total of 1 and failed
        // at 2 — the fixture was measuring the container fallback and calling it a retry.
        List<string> reads = [];
        SoundCache cache = Cache(reads, has: _ => false);

        cache.Sample("weapons/never_shipped.wav").ShouldBeNull();

        reads.ShouldNotBeEmpty("the first play must actually look for it");
        reads.Clear();

        for (int play = 0; play < 4; play++)
        {
            cache.Sample("weapons/never_shipped.wav").ShouldBeNull();
        }

        reads.ShouldBeEmpty();
        cache.Unopened.ShouldBe(1);
    }

    [Test]
    public void Sample_ForANameCarryingSoundchars_ReadsThePathWithoutThem()
    {
        // **Valve's prefixes are instructions to the engine, not part of the path** — ')' spatialised,
        // '#' a stream, and the rest. Left on, every one of them is a file that does not exist, so
        // the observable is the path actually asked for rather than whether a sample came back.
        List<string> reads = [];
        SoundCache cache = Cache(reads);

        cache.Sample(")ambient/indoors.wav");

        reads.ShouldBe(["sound/ambient/indoors.wav"]);
    }

    [Test]
    public void Sample_ForAPlainName_ReadsItUnchanged()
    {
        // The control for the strip: a name with no soundchars must arrive whole. Without this,
        // an implementation that chopped the first character off everything would pass the pair
        // above.
        List<string> reads = [];
        SoundCache cache = Cache(reads);

        cache.Sample("ambient/indoors.wav");

        reads.ShouldBe(["sound/ambient/indoors.wav"]);
    }

    [Test]
    public void Precache_OverAMixedList_SaysWhatArrivedAndWhatDidNot()
    {
        // **Both numbers, because they answer different questions.** The gap between them is how
        // many sounds the install could not supply, which is the difference between "the precache
        // worked" and "the precache found nothing to do" — one number cannot say which.
        SoundCache cache = Cache([], has: path => path.Contains("indoors", StringComparison.Ordinal));

        PrecacheResult result = cache.Precache(
            ["ambient/indoors.wav", "ambient/outdoors.wav", "ambient/nowhere.wav"]);

        result.Named.ShouldBe(3);
        result.Decoded.ShouldBe(1);
    }

    [Test]
    public void Precache_ForANameAlreadyDecoded_DoesNotReadItAgain()
    {
        // A precache runs after the soundscape catalog is read, and the two lists overlap. Reading
        // the overlap twice is the cost this type exists to remove.
        List<string> reads = [];
        SoundCache cache = Cache(reads);

        cache.Sample("ambient/indoors.wav");
        cache.Precache(["ambient/indoors.wav"]);

        reads.Count.ShouldBe(1);
    }

    [Test]
    public void Sample_WithNoName_Refuses()
    {
        Should.Throw<ArgumentNullException>(() => new SoundCache(NullLogger.Instance).Sample(null!));
    }

    [Test]
    public void Constructor_WithNoLogger_Refuses()
    {
        // Every miss here is reported rather than swallowed, so a null sink is a caller mistake
        // rather than a quiet mode.
        Should.Throw<ArgumentNullException>(() => new SoundCache(null!));
    }

    /// <summary>A cache over an install that answers a one-sample wave for whatever it has.</summary>
    /// <param name="reads">Records every path asked for, in order.</param>
    /// <param name="has">Which paths exist; everything, by default.</param>
    private static SoundCache Cache(List<string> reads, Func<string, bool>? has = null) =>
        new(NullLogger.Instance)
        {
            Read = path =>
            {
                reads.Add(path);

                return has is null || has(path) ? OneSample : null;
            },
        };

    /// <summary>A minimal 16-bit mono RIFF/WAVE carrying a single sample.</summary>
    private static byte[] OneSample => WaveBytes(16, 1, 22050, [0x01, 0x00]);

    /// <summary>A minimal RIFF/WAVE file, written by hand from the format rather than our reader.</summary>
    private static byte[] WaveBytes(int bits, int channels, int rate, byte[] data)
    {
        int blockAlign = channels * ((bits + 7) / 8);
        List<byte> file = [];

        void Ascii(string text) => file.AddRange(Encoding.ASCII.GetBytes(text));

        void U32(int value)
        {
            byte[] four = new byte[4];
            BinaryPrimitives.WriteUInt32LittleEndian(four, (uint)value);
            file.AddRange(four);
        }

        void U16(int value)
        {
            byte[] two = new byte[2];
            BinaryPrimitives.WriteUInt16LittleEndian(two, (ushort)value);
            file.AddRange(two);
        }

        Ascii("RIFF");
        U32(36 + data.Length);
        Ascii("WAVE");

        Ascii("fmt ");
        U32(16);
        U16(1);
        U16(channels);
        U32(rate);
        U32(rate * blockAlign);
        U16(blockAlign);
        U16(bits);

        Ascii("data");
        U32(data.Length);
        file.AddRange(data);

        return [.. file];
    }
}
