using System;
using System.Collections.Generic;

namespace Tf2DemoSalvage.Content.Assets;

/// <summary>
/// Valve's per-weapon activity tables — <c>CTFWeaponBase::ActivityOverride</c>.
/// </summary>
/// <remarks>
/// **A player's animations are named generically and rewritten by the weapon in hand.**
/// `CTFPlayerAnimState::TranslateActivity` (`tf_playeranimstate.cpp:124`) calls
/// `pWeapon->ActivityOverride( translateActivity, NULL )`, which walks the weapon's own
/// `acttable_t` — one table per role, twelve of them, in `tf_weaponbase.cpp:3660` onward. So
/// `ACT_MP_RELOAD_STAND` becomes `ACT_MP_RELOAD_STAND_PRIMARY` in a scattergun's hands and
/// `ACT_MP_RELOAD_STAND_SECONDARY` in a pistol's, and a model declares only the rewritten names.
///
/// **It is a TABLE and not a suffix rule, which is why this is transcribed rather than computed.**
/// Three entries in the primary table alone break any pattern you could write:
///
/// <code>
///   { ACT_MP_STAND_IDLE,                ACT_MP_STAND_PRIMARY,        false },  // IDLE → PRIMARY
///   { ACT_MP_CROUCH_DEPLOYED,           ACT_MP_CROUCHWALK_DEPLOYED,  false },  // CROUCH → CROUCHWALK
///   { ACT_MP_ATTACK_STAND_PRIMARYFIRE,  ACT_MP_ATTACK_STAND_PRIMARY, false },  // PRIMARYFIRE → PRIMARY
/// </code>
///
/// A first attempt at B284 appended the role as a string. That happens to be right for the reload
/// and jump-land families and wrong for every attack, which is a silent wrongness: an activity that
/// resolves to no sequence draws no gesture and logs nothing.
///
/// **Generated from the SDK, and a conformance test regenerates it.** The rows below were extracted
/// from `tf_weaponbase.cpp` rather than typed, and `WeaponActivityConformanceTests` parses the same
/// file and asserts the two agree — so this cannot drift from Valve without a red test, which is
/// the same arrangement `SdkCoverageTests` uses for the shader and lump denominators.
///
/// **Not implemented: the two overrides that sit either side of this one.**
/// `CTFPlayerAnimState::ActivityOverride` applies the player's own table first (the kart and taunt
/// states), and `CEconItemView::GetActivityOverride` applies a per-item one afterwards, which is
/// how a reskin animates differently. Both are named here rather than left to be discovered.
/// </remarks>
public static class WeaponActivityTable
{
    /// <summary>Every row, as <c>ROLE|from|to</c>.</summary>
    /// <remarks>
    /// **Stored as strings rather than as a nested dictionary literal** so the extraction that
    /// produced them and the test that re-extracts them compare the same shape. The lookup is built
    /// once, below.
    /// </remarks>
    private static readonly string[] Rows =
    [
        "PRIMARY|ACT_MP_STAND_IDLE|ACT_MP_STAND_PRIMARY",
        "PRIMARY|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_PRIMARY",
        "PRIMARY|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_PRIMARY",
        "PRIMARY|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED",
        "PRIMARY|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE",
        "PRIMARY|ACT_MP_RUN|ACT_MP_RUN_PRIMARY",
        "PRIMARY|ACT_MP_WALK|ACT_MP_WALK_PRIMARY",
        "PRIMARY|ACT_MP_AIRWALK|ACT_MP_AIRWALK_PRIMARY",
        "PRIMARY|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_PRIMARY",
        "PRIMARY|ACT_MP_JUMP|ACT_MP_JUMP_PRIMARY",
        "PRIMARY|ACT_MP_JUMP_START|ACT_MP_JUMP_START_PRIMARY",
        "PRIMARY|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_PRIMARY",
        "PRIMARY|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_PRIMARY",
        "PRIMARY|ACT_MP_SWIM|ACT_MP_SWIM_PRIMARY",
        "PRIMARY|ACT_MP_SWIM_DEPLOYED|ACT_MP_SWIM_DEPLOYED_PRIMARY",
        "PRIMARY|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_PRIMARY",
        "PRIMARY|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_PRIMARY",
        "PRIMARY|ACT_MP_ATTACK_STAND_PRIMARYFIRE_DEPLOYED|ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED",
        "PRIMARY|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_PRIMARY",
        "PRIMARY|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE_DEPLOYED|ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED",
        "PRIMARY|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_PRIMARY",
        "PRIMARY|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_PRIMARY",
        "PRIMARY|ACT_MP_RELOAD_STAND|ACT_MP_RELOAD_STAND_PRIMARY",
        "PRIMARY|ACT_MP_RELOAD_STAND_LOOP|ACT_MP_RELOAD_STAND_PRIMARY_LOOP",
        "PRIMARY|ACT_MP_RELOAD_STAND_END|ACT_MP_RELOAD_STAND_PRIMARY_END",
        "PRIMARY|ACT_MP_RELOAD_CROUCH|ACT_MP_RELOAD_CROUCH_PRIMARY",
        "PRIMARY|ACT_MP_RELOAD_CROUCH_LOOP|ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP",
        "PRIMARY|ACT_MP_RELOAD_CROUCH_END|ACT_MP_RELOAD_CROUCH_PRIMARY_END",
        "PRIMARY|ACT_MP_RELOAD_SWIM|ACT_MP_RELOAD_SWIM_PRIMARY",
        "PRIMARY|ACT_MP_RELOAD_SWIM_LOOP|ACT_MP_RELOAD_SWIM_PRIMARY_LOOP",
        "PRIMARY|ACT_MP_RELOAD_SWIM_END|ACT_MP_RELOAD_SWIM_PRIMARY_END",
        "PRIMARY|ACT_MP_RELOAD_AIRWALK|ACT_MP_RELOAD_AIRWALK_PRIMARY",
        "PRIMARY|ACT_MP_RELOAD_AIRWALK_LOOP|ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP",
        "PRIMARY|ACT_MP_RELOAD_AIRWALK_END|ACT_MP_RELOAD_AIRWALK_PRIMARY_END",
        "PRIMARY|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_PRIMARY",
        "PRIMARY|ACT_MP_GRENADE1_DRAW|ACT_MP_PRIMARY_GRENADE1_DRAW",
        "PRIMARY|ACT_MP_GRENADE1_IDLE|ACT_MP_PRIMARY_GRENADE1_IDLE",
        "PRIMARY|ACT_MP_GRENADE1_ATTACK|ACT_MP_PRIMARY_GRENADE1_ATTACK",
        "PRIMARY|ACT_MP_GRENADE2_DRAW|ACT_MP_PRIMARY_GRENADE2_DRAW",
        "PRIMARY|ACT_MP_GRENADE2_IDLE|ACT_MP_PRIMARY_GRENADE2_IDLE",
        "PRIMARY|ACT_MP_GRENADE2_ATTACK|ACT_MP_PRIMARY_GRENADE2_ATTACK",
        "PRIMARY|ACT_MP_ATTACK_STAND_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY|ACT_MP_ATTACK_CROUCH_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY|ACT_MP_ATTACK_SWIM_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY|ACT_MP_ATTACK_AIRWALK_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY",
        "PRIMARY|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY",
        "PRIMARY|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY",
        "PRIMARY|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY",
        "PRIMARY|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_PRIMARY",
        "PRIMARY|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_PRIMARY",
        "PRIMARY|ACT_MP_FALLING_STOMP|ACT_MP_FALLING_STOMP_PRIMARY",
        "SECONDARY|ACT_MP_STAND_IDLE|ACT_MP_STAND_SECONDARY",
        "SECONDARY|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_SECONDARY",
        "SECONDARY|ACT_MP_RUN|ACT_MP_RUN_SECONDARY",
        "SECONDARY|ACT_MP_WALK|ACT_MP_WALK_SECONDARY",
        "SECONDARY|ACT_MP_AIRWALK|ACT_MP_AIRWALK_SECONDARY",
        "SECONDARY|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_SECONDARY",
        "SECONDARY|ACT_MP_JUMP|ACT_MP_JUMP_SECONDARY",
        "SECONDARY|ACT_MP_JUMP_START|ACT_MP_JUMP_START_SECONDARY",
        "SECONDARY|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_SECONDARY",
        "SECONDARY|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_SECONDARY",
        "SECONDARY|ACT_MP_SWIM|ACT_MP_SWIM_SECONDARY",
        "SECONDARY|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_SECONDARY",
        "SECONDARY|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_SECONDARY",
        "SECONDARY|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_SECONDARY",
        "SECONDARY|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_SECONDARY",
        "SECONDARY|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_SECONDARY",
        "SECONDARY|ACT_MP_RELOAD_STAND|ACT_MP_RELOAD_STAND_SECONDARY",
        "SECONDARY|ACT_MP_RELOAD_STAND_LOOP|ACT_MP_RELOAD_STAND_SECONDARY_LOOP",
        "SECONDARY|ACT_MP_RELOAD_STAND_END|ACT_MP_RELOAD_STAND_SECONDARY_END",
        "SECONDARY|ACT_MP_RELOAD_CROUCH|ACT_MP_RELOAD_CROUCH_SECONDARY",
        "SECONDARY|ACT_MP_RELOAD_CROUCH_LOOP|ACT_MP_RELOAD_CROUCH_SECONDARY_LOOP",
        "SECONDARY|ACT_MP_RELOAD_CROUCH_END|ACT_MP_RELOAD_CROUCH_SECONDARY_END",
        "SECONDARY|ACT_MP_RELOAD_SWIM|ACT_MP_RELOAD_SWIM_SECONDARY",
        "SECONDARY|ACT_MP_RELOAD_SWIM_LOOP|ACT_MP_RELOAD_SWIM_SECONDARY_LOOP",
        "SECONDARY|ACT_MP_RELOAD_SWIM_END|ACT_MP_RELOAD_SWIM_SECONDARY_END",
        "SECONDARY|ACT_MP_RELOAD_AIRWALK|ACT_MP_RELOAD_AIRWALK_SECONDARY",
        "SECONDARY|ACT_MP_RELOAD_AIRWALK_LOOP|ACT_MP_RELOAD_AIRWALK_SECONDARY_LOOP",
        "SECONDARY|ACT_MP_RELOAD_AIRWALK_END|ACT_MP_RELOAD_AIRWALK_SECONDARY_END",
        "SECONDARY|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_SECONDARY",
        "SECONDARY|ACT_MP_GRENADE1_DRAW|ACT_MP_SECONDARY_GRENADE1_DRAW",
        "SECONDARY|ACT_MP_GRENADE1_IDLE|ACT_MP_SECONDARY_GRENADE1_IDLE",
        "SECONDARY|ACT_MP_GRENADE1_ATTACK|ACT_MP_SECONDARY_GRENADE1_ATTACK",
        "SECONDARY|ACT_MP_GRENADE2_DRAW|ACT_MP_SECONDARY_GRENADE2_DRAW",
        "SECONDARY|ACT_MP_GRENADE2_IDLE|ACT_MP_SECONDARY_GRENADE2_IDLE",
        "SECONDARY|ACT_MP_GRENADE2_ATTACK|ACT_MP_SECONDARY_GRENADE2_ATTACK",
        "SECONDARY|ACT_MP_ATTACK_STAND_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY|ACT_MP_ATTACK_CROUCH_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY|ACT_MP_ATTACK_SWIM_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY|ACT_MP_ATTACK_AIRWALK_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY",
        "SECONDARY|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY",
        "SECONDARY|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY",
        "SECONDARY|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY",
        "SECONDARY|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_SECONDARY",
        "SECONDARY|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_SECONDARY",
        "PRIMARY2|ACT_MP_STAND_IDLE|ACT_MP_STAND_PRIMARY",
        "PRIMARY2|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_PRIMARY",
        "PRIMARY2|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_PRIMARY",
        "PRIMARY2|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED",
        "PRIMARY2|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE",
        "PRIMARY2|ACT_MP_RUN|ACT_MP_RUN_PRIMARY",
        "PRIMARY2|ACT_MP_WALK|ACT_MP_WALK_PRIMARY",
        "PRIMARY2|ACT_MP_AIRWALK|ACT_MP_AIRWALK_PRIMARY",
        "PRIMARY2|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_PRIMARY",
        "PRIMARY2|ACT_MP_JUMP|ACT_MP_JUMP_PRIMARY",
        "PRIMARY2|ACT_MP_JUMP_START|ACT_MP_JUMP_START_PRIMARY",
        "PRIMARY2|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_PRIMARY",
        "PRIMARY2|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_PRIMARY",
        "PRIMARY2|ACT_MP_SWIM|ACT_MP_SWIM_PRIMARY",
        "PRIMARY2|ACT_MP_SWIM_DEPLOYED|ACT_MP_SWIM_DEPLOYED_PRIMARY",
        "PRIMARY2|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_PRIMARY",
        "PRIMARY2|ACT_MP_ATTACK_STAND_PRIMARY_SUPER|ACT_MP_ATTACK_STAND_PRIMARY_SUPER",
        "PRIMARY2|ACT_MP_ATTACK_CROUCH_PRIMARY_SUPER|ACT_MP_ATTACK_CROUCH_PRIMARY_SUPER",
        "PRIMARY2|ACT_MP_ATTACK_SWIM_PRIMARY_SUPER|ACT_MP_ATTACK_SWIM_PRIMARY_SUPER",
        "PRIMARY2|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_PRIMARY",
        "PRIMARY2|ACT_MP_RELOAD_STAND|ACT_MP_RELOAD_STAND_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_RELOAD_STAND_LOOP|ACT_MP_RELOAD_STAND_PRIMARY_LOOP_ALT",
        "PRIMARY2|ACT_MP_RELOAD_STAND_END|ACT_MP_RELOAD_STAND_PRIMARY_END_ALT",
        "PRIMARY2|ACT_MP_RELOAD_CROUCH|ACT_MP_RELOAD_CROUCH_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_RELOAD_CROUCH_LOOP|ACT_MP_RELOAD_CROUCH_PRIMARY_LOOP_ALT",
        "PRIMARY2|ACT_MP_RELOAD_CROUCH_END|ACT_MP_RELOAD_CROUCH_PRIMARY_END_ALT",
        "PRIMARY2|ACT_MP_RELOAD_SWIM|ACT_MP_RELOAD_SWIM_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_RELOAD_SWIM_LOOP|ACT_MP_RELOAD_SWIM_PRIMARY_LOOP",
        "PRIMARY2|ACT_MP_RELOAD_SWIM_END|ACT_MP_RELOAD_SWIM_PRIMARY_END",
        "PRIMARY2|ACT_MP_RELOAD_AIRWALK|ACT_MP_RELOAD_AIRWALK_PRIMARY_ALT",
        "PRIMARY2|ACT_MP_RELOAD_AIRWALK_LOOP|ACT_MP_RELOAD_AIRWALK_PRIMARY_LOOP_ALT",
        "PRIMARY2|ACT_MP_RELOAD_AIRWALK_END|ACT_MP_RELOAD_AIRWALK_PRIMARY_END_ALT",
        "PRIMARY2|ACT_MP_ATTACK_STAND_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY2|ACT_MP_ATTACK_CROUCH_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY2|ACT_MP_ATTACK_SWIM_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY2|ACT_MP_ATTACK_AIRWALK_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "PRIMARY2|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_PRIMARY",
        "PRIMARY2|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_PRIMARY",
        "PRIMARY2|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_PRIMARY",
        "PRIMARY2|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_PRIMARY",
        "PRIMARY2|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_PRIMARY",
        "PRIMARY2|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_PRIMARY",
        "SECONDARY2|ACT_MP_STAND_IDLE|ACT_MP_STAND_SECONDARY2",
        "SECONDARY2|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_SECONDARY2",
        "SECONDARY2|ACT_MP_RUN|ACT_MP_RUN_SECONDARY2",
        "SECONDARY2|ACT_MP_WALK|ACT_MP_WALK_SECONDARY2",
        "SECONDARY2|ACT_MP_AIRWALK|ACT_MP_AIRWALK_SECONDARY2",
        "SECONDARY2|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_SECONDARY2",
        "SECONDARY2|ACT_MP_JUMP|ACT_MP_JUMP_SECONDARY2",
        "SECONDARY2|ACT_MP_JUMP_START|ACT_MP_JUMP_START_SECONDARY2",
        "SECONDARY2|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_SECONDARY2",
        "SECONDARY2|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_SECONDARY2",
        "SECONDARY2|ACT_MP_SWIM|ACT_MP_SWIM_SECONDARY2",
        "SECONDARY2|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_SECONDARY2",
        "SECONDARY2|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_SECONDARY2",
        "SECONDARY2|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_SECONDARY2",
        "SECONDARY2|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_SECONDARY2",
        "SECONDARY2|ACT_MP_RELOAD_STAND|ACT_MP_RELOAD_STAND_SECONDARY2",
        "SECONDARY2|ACT_MP_RELOAD_STAND_LOOP|ACT_MP_RELOAD_STAND_SECONDARY2_LOOP",
        "SECONDARY2|ACT_MP_RELOAD_STAND_END|ACT_MP_RELOAD_STAND_SECONDARY2_END",
        "SECONDARY2|ACT_MP_RELOAD_CROUCH|ACT_MP_RELOAD_CROUCH_SECONDARY2",
        "SECONDARY2|ACT_MP_RELOAD_CROUCH_LOOP|ACT_MP_RELOAD_CROUCH_SECONDARY2_LOOP",
        "SECONDARY2|ACT_MP_RELOAD_CROUCH_END|ACT_MP_RELOAD_CROUCH_SECONDARY2_END",
        "SECONDARY2|ACT_MP_RELOAD_SWIM|ACT_MP_RELOAD_SWIM_SECONDARY2",
        "SECONDARY2|ACT_MP_RELOAD_SWIM_LOOP|ACT_MP_RELOAD_SWIM_SECONDARY2_LOOP",
        "SECONDARY2|ACT_MP_RELOAD_SWIM_END|ACT_MP_RELOAD_SWIM_SECONDARY2_END",
        "SECONDARY2|ACT_MP_RELOAD_AIRWALK|ACT_MP_RELOAD_AIRWALK_SECONDARY2",
        "SECONDARY2|ACT_MP_RELOAD_AIRWALK_LOOP|ACT_MP_RELOAD_AIRWALK_SECONDARY2_LOOP",
        "SECONDARY2|ACT_MP_RELOAD_AIRWALK_END|ACT_MP_RELOAD_AIRWALK_SECONDARY2_END",
        "SECONDARY2|ACT_MP_ATTACK_STAND_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY2|ACT_MP_ATTACK_CROUCH_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY2|ACT_MP_ATTACK_SWIM_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY2|ACT_MP_ATTACK_AIRWALK_GRENADE|ACT_MP_ATTACK_STAND_GRENADE",
        "SECONDARY2|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_SECONDARY",
        "SECONDARY2|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_SECONDARY",
        "SECONDARY2|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_SECONDARY",
        "SECONDARY2|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_SECONDARY",
        "SECONDARY2|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_SECONDARY",
        "SECONDARY2|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_SECONDARY",
        "MELEE|ACT_MP_STAND_IDLE|ACT_MP_STAND_MELEE",
        "MELEE|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_MELEE",
        "MELEE|ACT_MP_RUN|ACT_MP_RUN_MELEE",
        "MELEE|ACT_MP_WALK|ACT_MP_WALK_MELEE",
        "MELEE|ACT_MP_AIRWALK|ACT_MP_AIRWALK_MELEE",
        "MELEE|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_MELEE",
        "MELEE|ACT_MP_JUMP|ACT_MP_JUMP_MELEE",
        "MELEE|ACT_MP_JUMP_START|ACT_MP_JUMP_START_MELEE",
        "MELEE|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_MELEE",
        "MELEE|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_MELEE",
        "MELEE|ACT_MP_SWIM|ACT_MP_SWIM_MELEE",
        "MELEE|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_MELEE",
        "MELEE|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_MELEE",
        "MELEE|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_MELEE",
        "MELEE|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_MELEE",
        "MELEE|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_MELEE",
        "MELEE|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_MELEE_SECONDARY",
        "MELEE|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_MELEE_SECONDARY",
        "MELEE|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_MELEE",
        "MELEE|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_MELEE",
        "MELEE|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_MELEE",
        "MELEE|ACT_MP_GRENADE1_DRAW|ACT_MP_MELEE_GRENADE1_DRAW",
        "MELEE|ACT_MP_GRENADE1_IDLE|ACT_MP_MELEE_GRENADE1_IDLE",
        "MELEE|ACT_MP_GRENADE1_ATTACK|ACT_MP_MELEE_GRENADE1_ATTACK",
        "MELEE|ACT_MP_GRENADE2_DRAW|ACT_MP_MELEE_GRENADE2_DRAW",
        "MELEE|ACT_MP_GRENADE2_IDLE|ACT_MP_MELEE_GRENADE2_IDLE",
        "MELEE|ACT_MP_GRENADE2_ATTACK|ACT_MP_MELEE_GRENADE2_ATTACK",
        "MELEE|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_MELEE",
        "MELEE|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_MELEE",
        "MELEE|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_MELEE",
        "MELEE|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_MELEE",
        "MELEE|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_MELEE",
        "MELEE|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_MELEE",
        "MELEE|ACT_MP_FALLING_STOMP|ACT_MP_FALLING_STOMP_MELEE",
        "ITEM1|ACT_MP_STAND_IDLE|ACT_MP_STAND_ITEM1",
        "ITEM1|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_ITEM1",
        "ITEM1|ACT_MP_RUN|ACT_MP_RUN_ITEM1",
        "ITEM1|ACT_MP_WALK|ACT_MP_WALK_ITEM1",
        "ITEM1|ACT_MP_AIRWALK|ACT_MP_AIRWALK_ITEM1",
        "ITEM1|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_ITEM1",
        "ITEM1|ACT_MP_JUMP|ACT_MP_JUMP_ITEM1",
        "ITEM1|ACT_MP_JUMP_START|ACT_MP_JUMP_START_ITEM1",
        "ITEM1|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_ITEM1",
        "ITEM1|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_ITEM1",
        "ITEM1|ACT_MP_SWIM|ACT_MP_SWIM_ITEM1",
        "ITEM1|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_ITEM1",
        "ITEM1|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_ITEM1",
        "ITEM1|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM1",
        "ITEM1|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_ITEM1",
        "ITEM1|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM1",
        "ITEM1|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_ITEM1_SECONDARY",
        "ITEM1|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM1_SECONDARY",
        "ITEM1|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_ITEM1",
        "ITEM1|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM1",
        "ITEM1|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_ITEM1",
        "ITEM1|ACT_MP_DEPLOYED_IDLE|ACT_MP_DEPLOYED_IDLE_ITEM1",
        "ITEM1|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED_ITEM1",
        "ITEM1|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM1",
        "ITEM1|ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED|ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED_ITEM1",
        "ITEM1|ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED|ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED_ITEM1",
        "ITEM1|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_ITEM1",
        "ITEM1|ACT_MP_GRENADE1_DRAW|ACT_MP_ITEM1_GRENADE1_DRAW",
        "ITEM1|ACT_MP_GRENADE1_IDLE|ACT_MP_ITEM1_GRENADE1_IDLE",
        "ITEM1|ACT_MP_GRENADE1_ATTACK|ACT_MP_ITEM1_GRENADE1_ATTACK",
        "ITEM1|ACT_MP_GRENADE2_DRAW|ACT_MP_ITEM1_GRENADE2_DRAW",
        "ITEM1|ACT_MP_GRENADE2_IDLE|ACT_MP_ITEM1_GRENADE2_IDLE",
        "ITEM1|ACT_MP_GRENADE2_ATTACK|ACT_MP_ITEM1_GRENADE2_ATTACK",
        "ITEM1|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_ITEM1",
        "ITEM1|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_ITEM1",
        "ITEM1|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_ITEM1",
        "ITEM1|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_ITEM1",
        "ITEM1|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_ITEM1",
        "ITEM1|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_ITEM1",
        "ITEM2|ACT_MP_STAND_IDLE|ACT_MP_STAND_ITEM2",
        "ITEM2|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_ITEM2",
        "ITEM2|ACT_MP_RUN|ACT_MP_RUN_ITEM2",
        "ITEM2|ACT_MP_WALK|ACT_MP_WALK_ITEM2",
        "ITEM2|ACT_MP_AIRWALK|ACT_MP_AIRWALK_ITEM2",
        "ITEM2|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_ITEM2",
        "ITEM2|ACT_MP_JUMP|ACT_MP_JUMP_ITEM2",
        "ITEM2|ACT_MP_JUMP_START|ACT_MP_JUMP_START_ITEM2",
        "ITEM2|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_ITEM2",
        "ITEM2|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_ITEM2",
        "ITEM2|ACT_MP_SWIM|ACT_MP_SWIM_ITEM2",
        "ITEM2|ACT_MP_AIRWALK|ACT_MP_AIRWALK_ITEM2",
        "ITEM2|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_ITEM2",
        "ITEM2|ACT_MP_RELOAD_STAND|ACT_MP_RELOAD_STAND_ITEM2",
        "ITEM2|ACT_MP_RELOAD_CROUCH|ACT_MP_RELOAD_CROUCH_ITEM2",
        "ITEM2|ACT_MP_RELOAD_SWIM|ACT_MP_RELOAD_SWIM_ITEM2",
        "ITEM2|ACT_MP_RELOAD_AIRWALK|ACT_MP_RELOAD_AIRWALK_ITEM2",
        "ITEM2|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_ITEM2",
        "ITEM2|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM2",
        "ITEM2|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_ITEM2",
        "ITEM2|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM2",
        "ITEM2|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_ITEM2",
        "ITEM2|ACT_MP_DEPLOYED_IDLE|ACT_MP_DEPLOYED_IDLE_ITEM2",
        "ITEM2|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED_ITEM2",
        "ITEM2|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM2",
        "ITEM2|ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED|ACT_MP_ATTACK_STAND_PRIMARY_DEPLOYED_ITEM2",
        "ITEM2|ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED|ACT_MP_ATTACK_CROUCH_PRIMARY_DEPLOYED_ITEM2",
        "ITEM2|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_ITEM2_SECONDARY",
        "ITEM2|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM2_SECONDARY",
        "ITEM2|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_ITEM2",
        "ITEM2|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM2",
        "ITEM2|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_ITEM2",
        "ITEM2|ACT_MP_GRENADE1_DRAW|ACT_MP_ITEM2_GRENADE1_DRAW",
        "ITEM2|ACT_MP_GRENADE1_IDLE|ACT_MP_ITEM2_GRENADE1_IDLE",
        "ITEM2|ACT_MP_GRENADE1_ATTACK|ACT_MP_ITEM2_GRENADE1_ATTACK",
        "ITEM2|ACT_MP_GRENADE2_DRAW|ACT_MP_ITEM2_GRENADE2_DRAW",
        "ITEM2|ACT_MP_GRENADE2_IDLE|ACT_MP_ITEM2_GRENADE2_IDLE",
        "ITEM2|ACT_MP_GRENADE2_ATTACK|ACT_MP_ITEM2_GRENADE2_ATTACK",
        "ITEM2|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_ITEM2",
        "ITEM2|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_ITEM2",
        "ITEM2|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_ITEM2",
        "ITEM2|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_ITEM2",
        "ITEM2|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_ITEM2",
        "ITEM2|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_ITEM2",
        "ITEM3|ACT_MP_STAND_IDLE|ACT_MP_STAND_ITEM3",
        "ITEM3|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_ITEM3",
        "ITEM3|ACT_MP_RUN|ACT_MP_RUN_ITEM3",
        "ITEM3|ACT_MP_WALK|ACT_MP_WALK_ITEM3",
        "ITEM3|ACT_MP_AIRWALK|ACT_MP_AIRWALK_ITEM3",
        "ITEM3|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_ITEM3",
        "ITEM3|ACT_MP_JUMP|ACT_MP_JUMP_ITEM3",
        "ITEM3|ACT_MP_JUMP_START|ACT_MP_JUMP_START_ITEM3",
        "ITEM3|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_ITEM3",
        "ITEM3|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_ITEM3",
        "ITEM3|ACT_MP_SWIM|ACT_MP_SWIM_ITEM3",
        "ITEM3|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_ITEM3",
        "ITEM3|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM3",
        "ITEM3|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_ITEM3",
        "ITEM3|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM3",
        "ITEM3|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_ITEM3_SECONDARY",
        "ITEM3|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM3_SECONDARY",
        "ITEM3|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_ITEM3",
        "ITEM3|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM3",
        "ITEM3|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_ITEM3",
        "ITEM3|ACT_MP_DEPLOYED_IDLE|ACT_MP_DEPLOYED_IDLE_ITEM3",
        "ITEM3|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED_ITEM3",
        "ITEM3|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM3",
        "ITEM4|ACT_MP_STAND_IDLE|ACT_MP_STAND_ITEM4",
        "ITEM4|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_ITEM4",
        "ITEM4|ACT_MP_RUN|ACT_MP_RUN_ITEM4",
        "ITEM4|ACT_MP_WALK|ACT_MP_WALK_ITEM4",
        "ITEM4|ACT_MP_AIRWALK|ACT_MP_AIRWALK_ITEM4",
        "ITEM4|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_ITEM4",
        "ITEM4|ACT_MP_JUMP|ACT_MP_JUMP_ITEM4",
        "ITEM4|ACT_MP_JUMP_START|ACT_MP_JUMP_START_ITEM4",
        "ITEM4|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_ITEM4",
        "ITEM4|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_ITEM4",
        "ITEM4|ACT_MP_SWIM|ACT_MP_SWIM_ITEM4",
        "ITEM4|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_ITEM4",
        "ITEM4|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM4",
        "ITEM4|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_ITEM4",
        "ITEM4|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM4",
        "ITEM4|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_ITEM4_SECONDARY",
        "ITEM4|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_ITEM4_SECONDARY",
        "ITEM4|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_ITEM4",
        "ITEM4|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_ITEM4",
        "ITEM4|ACT_MP_DEPLOYED|ACT_MP_DEPLOYED_ITEM4",
        "ITEM4|ACT_MP_DEPLOYED_IDLE|ACT_MP_DEPLOYED_IDLE_ITEM4",
        "ITEM4|ACT_MP_CROUCH_DEPLOYED|ACT_MP_CROUCHWALK_DEPLOYED_ITEM4",
        "ITEM4|ACT_MP_CROUCH_DEPLOYED_IDLE|ACT_MP_CROUCH_DEPLOYED_IDLE_ITEM4",
        "BUILDING|ACT_MP_STAND_IDLE|ACT_MP_STAND_BUILDING",
        "BUILDING|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_BUILDING",
        "BUILDING|ACT_MP_RUN|ACT_MP_RUN_BUILDING",
        "BUILDING|ACT_MP_WALK|ACT_MP_WALK_BUILDING",
        "BUILDING|ACT_MP_AIRWALK|ACT_MP_AIRWALK_BUILDING",
        "BUILDING|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_BUILDING",
        "BUILDING|ACT_MP_JUMP|ACT_MP_JUMP_BUILDING",
        "BUILDING|ACT_MP_JUMP_START|ACT_MP_JUMP_START_BUILDING",
        "BUILDING|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_BUILDING",
        "BUILDING|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_BUILDING",
        "BUILDING|ACT_MP_SWIM|ACT_MP_SWIM_BUILDING",
        "BUILDING|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_BUILDING",
        "BUILDING|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_BUILDING",
        "BUILDING|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_BUILDING",
        "BUILDING|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_BUILDING",
        "BUILDING|ACT_MP_ATTACK_STAND_GRENADE|ACT_MP_ATTACK_STAND_GRENADE_BUILDING",
        "BUILDING|ACT_MP_ATTACK_CROUCH_GRENADE|ACT_MP_ATTACK_STAND_GRENADE_BUILDING",
        "BUILDING|ACT_MP_ATTACK_SWIM_GRENADE|ACT_MP_ATTACK_STAND_GRENADE_BUILDING",
        "BUILDING|ACT_MP_ATTACK_AIRWALK_GRENADE|ACT_MP_ATTACK_STAND_GRENADE_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_BUILDING",
        "BUILDING|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_BUILDING",
        "PDA|ACT_MP_STAND_IDLE|ACT_MP_STAND_PDA",
        "PDA|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_PDA",
        "PDA|ACT_MP_RUN|ACT_MP_RUN_PDA",
        "PDA|ACT_MP_WALK|ACT_MP_WALK_PDA",
        "PDA|ACT_MP_AIRWALK|ACT_MP_AIRWALK_PDA",
        "PDA|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_PDA",
        "PDA|ACT_MP_JUMP|ACT_MP_JUMP_PDA",
        "PDA|ACT_MP_JUMP_START|ACT_MP_JUMP_START_PDA",
        "PDA|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_PDA",
        "PDA|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_PDA",
        "PDA|ACT_MP_SWIM|ACT_MP_SWIM_PDA",
        "PDA|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_PDA",
        "PDA|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_PDA",
        "PDA|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_PDA",
        "PDA|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_PDA",
        "PDA|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_PDA",
        "PDA|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_PDA",
        "PDA|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_PDA",
        "PDA|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_PDA",
        "MELEEALLCLASS|ACT_MP_STAND_IDLE|ACT_MP_STAND_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_CROUCH_IDLE|ACT_MP_CROUCH_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_RUN|ACT_MP_RUN_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_WALK|ACT_MP_WALK_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_AIRWALK|ACT_MP_AIRWALK_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_CROUCHWALK|ACT_MP_CROUCHWALK_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_JUMP|ACT_MP_JUMP_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_JUMP_START|ACT_MP_JUMP_START_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_JUMP_FLOAT|ACT_MP_JUMP_FLOAT_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_JUMP_LAND|ACT_MP_JUMP_LAND_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_SWIM|ACT_MP_SWIM_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_DOUBLEJUMP_CROUCH|ACT_MP_DOUBLEJUMP_CROUCH_MELEE",
        "MELEEALLCLASS|ACT_MP_ATTACK_STAND_PRIMARYFIRE|ACT_MP_ATTACK_STAND_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_ATTACK_CROUCH_PRIMARYFIRE|ACT_MP_ATTACK_CROUCH_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_ATTACK_SWIM_PRIMARYFIRE|ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_ATTACK_AIRWALK_PRIMARYFIRE|ACT_MP_ATTACK_AIRWALK_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_ATTACK_STAND_SECONDARYFIRE|ACT_MP_ATTACK_STAND_MELEE_SECONDARY",
        "MELEEALLCLASS|ACT_MP_ATTACK_CROUCH_SECONDARYFIRE|ACT_MP_ATTACK_CROUCH_MELEE_SECONDARY",
        "MELEEALLCLASS|ACT_MP_ATTACK_SWIM_SECONDARYFIRE|ACT_MP_ATTACK_SWIM_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_ATTACK_AIRWALK_SECONDARYFIRE|ACT_MP_ATTACK_AIRWALK_MELEE_ALLCLASS",
        "MELEEALLCLASS|ACT_MP_GESTURE_FLINCH|ACT_MP_GESTURE_FLINCH_MELEE",
        "MELEEALLCLASS|ACT_MP_GRENADE1_DRAW|ACT_MP_MELEE_GRENADE1_DRAW",
        "MELEEALLCLASS|ACT_MP_GRENADE1_IDLE|ACT_MP_MELEE_GRENADE1_IDLE",
        "MELEEALLCLASS|ACT_MP_GRENADE1_ATTACK|ACT_MP_MELEE_GRENADE1_ATTACK",
        "MELEEALLCLASS|ACT_MP_GRENADE2_DRAW|ACT_MP_MELEE_GRENADE2_DRAW",
        "MELEEALLCLASS|ACT_MP_GRENADE2_IDLE|ACT_MP_MELEE_GRENADE2_IDLE",
        "MELEEALLCLASS|ACT_MP_GRENADE2_ATTACK|ACT_MP_MELEE_GRENADE2_ATTACK",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_HANDMOUTH|ACT_MP_GESTURE_VC_HANDMOUTH_MELEE",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_FINGERPOINT|ACT_MP_GESTURE_VC_FINGERPOINT_MELEE",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_FISTPUMP|ACT_MP_GESTURE_VC_FISTPUMP_MELEE",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_THUMBSUP|ACT_MP_GESTURE_VC_THUMBSUP_MELEE",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_NODYES|ACT_MP_GESTURE_VC_NODYES_MELEE",
        "MELEEALLCLASS|ACT_MP_GESTURE_VC_NODNO|ACT_MP_GESTURE_VC_NODNO_MELEE",
    ];

    private static readonly Dictionary<string, Dictionary<string, string>> ByRole = Build();

    /// <summary>How many rows the table carries, for a test that counts.</summary>
    public static int Count => Rows.Length;

    /// <summary>The roles the table names.</summary>
    public static IReadOnlyCollection<string> Roles => ByRole.Keys;

    /// <summary>Rewrites one activity for the weapon role holding it.</summary>
    /// <param name="role">The weapon's role — <c>PRIMARY</c>, <c>MELEE</c>, <c>ITEM2</c>.</param>
    /// <param name="activity">The generic activity the animation state asked for.</param>
    /// <returns>The weapon's own name for it, or <paramref name="activity"/> unchanged.</returns>
    /// <remarks>
    /// **Unchanged is the right answer for a miss**, and it is Valve's:
    /// `CBaseCombatWeapon::ActivityOverride` returns what it was given when the table has no row
    /// (`basecombatweapon_shared.cpp`), so an activity no weapon rewrites — a flinch — reaches the
    /// model under its own name.
    /// </remarks>
    public static string Override(string role, string activity)
    {
        ArgumentNullException.ThrowIfNull(role);
        ArgumentNullException.ThrowIfNull(activity);

        return ByRole.TryGetValue(role, out Dictionary<string, string>? table) &&
            table.TryGetValue(activity, out string? mapped)
                ? mapped
                : activity;
    }

    /// <summary>Every row for one role, for the conformance test to compare against.</summary>
    /// <param name="role">The role.</param>
    /// <returns>Its table, or an empty one.</returns>
    public static IReadOnlyDictionary<string, string> For(string role)
    {
        ArgumentNullException.ThrowIfNull(role);

        return ByRole.TryGetValue(role, out Dictionary<string, string>? table)
            ? table
            : new Dictionary<string, string>(StringComparer.Ordinal);
    }

    /// <summary>Indexes the rows by role and source activity.</summary>
    /// <returns>The lookup.</returns>
    /// <remarks>
    /// **The FIRST row for a pair wins, which is what a linear table walk does.**
    /// `ActivityOverride` returns on its first match, so a table listing a source twice uses the
    /// earlier entry — and at least one of Valve's does.
    /// </remarks>
    private static Dictionary<string, Dictionary<string, string>> Build()
    {
        Dictionary<string, Dictionary<string, string>> built = new(StringComparer.Ordinal);

        foreach (string row in Rows)
        {
            string[] parts = row.Split('|');

            if (parts.Length != 3)
            {
                continue;
            }

            if (!built.TryGetValue(parts[0], out Dictionary<string, string>? table))
            {
                table = new Dictionary<string, string>(StringComparer.Ordinal);
                built[parts[0]] = table;
            }

            _ = table.TryAdd(parts[1], parts[2]);
        }

        return built;
    }
}
